%YAML 1.2
---
# Baidu openapi, https://tongji.baidu.com/api/manual/Chapter2/openapi.html
baidu:
  api_key: your_api_key
  secret_key: your_secret_key
  auth_code: your_auth_code

# Redis
redis:
  host: localhost
  port: 6379
  db: 0
  password: ''

# MongoDB (optional)
mongodb:
  enable: false # trun on if you want to use MongoDB.
  uri: mongodb://localhost:27017

# PostgreSQL (optional, for demo)
postgresql:
  host: localhost
  port: 5432
  dbname: website_traffic
  username: postgres
  password: 123456

# Kibana (optional, for demo)
kibana:
  scheme: http
  host: localhost
  port: 5601
  username: elastic
  password: 123456
